# Add this new section to your existing config.yaml
# ADD AT THE END OF THE FILE:

# News Scraping Configuration
news_scraping:
  enabled: true
  max_articles: 50
  refresh_interval: 60  # seconds
  sources:
    - bloomberg
    - reuters
    - cnbc
    - marketwatch
    - yahoo
    - coinmarketcap
    
# Cryptocurrency Monitoring
crypto_monitoring:
  enabled: true
  default_cryptos:
    - BTC-USD
    - ETH-USD
    - BNB-USD
    - SOL-USD
    - XRP-USD
  max_cryptos: 100
  
# Market Prediction Weights
prediction_weights:
  news_sentiment: 0.4  # 40%
  technical_trend: 0.3  # 30%
  rsi_analysis: 0.2    # 20%
  volume_signal: 0.1   # 10%